# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: test

on: push

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Show version number
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - uses: johnnybenson/package-json-versioned-action@v1.0.5
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: echo "has-updated -- ${{ steps.package-json.outputs.has-updated }}"
      - run: echo "previous-version -- ${{ steps.package-json.outputs.previous-version }}"
      - run: echo "version -- ${{ steps.package-json.outputs.version }}"