# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Show version number
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
            echo "Published version: ${{ steps.cpv.outputs.published-version }}"

      - name: Is New
        if: steps.cpv.outputs.is-new-version == 'true'
        run: echo "updated, ${{steps.cpv.outputs.committed-version}}, ${{ steps.cpv.outputs.published-version }}"

      - name: Is Old
        if: steps.cpv.outputs.is-new-version == 'false'
        run: echo "${{steps.cpv.outputs.committed-version}}, ${{ steps.cpv.outputs.published-version }}"