# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Show version number
        run: echo "${{ steps.package-version.outputs.current-version}}"

      - name: get-version-from-package-json
        uses: polyseam/get-version-from-package-json@v.1.0.0
        id: get-version-from-package-json
        with:
          path-to-file: 'https://raw.githubusercontent.com/huibizhang/CodeSnap-plus/master/package.json'
      - name: print-version
        run: echo "The version key in your json is ${{steps.get-version-from-package-json.outputs.version}}"