# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: vsce_publish

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  checking:
    name: "Checking"
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'dev' }}
    outputs:
      output1: ${{ steps.package-json.outputs.has-updated }}
      output2: ${{ steps.package-json.outputs.previous-version }}
      output3: ${{ steps.package-json.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: johnnybenson/package-json-versioned-action@v1.0.5
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  publish-vsce:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: checking
    if: ${{ needs.test.outputs.output2 != needs.test.outputs.output3 }}
    steps:
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

  canceler:
    name: "Cancel"
    runs-on: ubuntu-latest
    needs: checking
    if: ${{ needs.test.outputs.output2 == needs.test.outputs.output3 }}
    steps:
      - uses: vishnudxb/cancel-workflow@v1.2
        with:
          repo: huibizhang/CodeSnap-plus
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

  